[package]
name = "oasystem"
edition = "2024"

[dependencies]
openaction = "2.1"
serde = "1.0"
tokio = { version = "1.47", features = ["rt-multi-thread", "macros", "time"] }
log = "0.4"
simplelog = "0.12"
sysinfo = "0.37"
gfxinfo = { version = "0.1", features = ["default"] }
